language: go
cache:
  directories:
    - $GOCACHE
    - $GOPATH/pkg/mod
    - $GOPATH/src/github.com/golang
    - $GOPATH/src/github.com/prometheus/client_golang/prometheus

go:
  - "1.13.x"

env:
  global:
    - GOCACHE=$HOME/.go-build

sudo: required

jobs:
  include:
    - stage: Build
      script:
        - make lint
        - make build
